# Generated by Django 3.0.4 on 2020-03-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
            options={
                'unique_together': {('code', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
            ],
            options={
                'unique_together': {('mod', 'pro')},
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.relation')),
            ],
        ),
    ]
