# Generated by Django 3.0.4 on 2020-03-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200323_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='pro_id',
            field=models.CharField(default='a', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
